---
- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: restart xinas-nfs-helper
  ansible.builtin.service:
    name: xinas-nfs-helper
    state: restarted

- name: restart sshd
  ansible.builtin.service:
    name: ssh    # Ubuntu uses "ssh", not "sshd"
    state: restarted
